# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1489148bc139883dfc30ed2c005b75b819d439239d6c68788fbe8a33a108e4de6b1909b0b1a802d22db73e56d8e9e02081f086917905306806659154e055d23

test:
  secret_key_base: 1efa23a3b05cd1b81429087fb2e56c06ffacd6b930a9dea51cfea23734b4f93a10ee49d4e880a9cbbfa8e71feb12063eda0ceb71f88e7677f659cb3c38f8225e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
